### PR TITLE
Added random food function

### PR DESCRIPTION
**Pull request by OmDharme**

### CODE REVIEW

**Review by harikanani — APPROVED** [review]

**Comment by Nitesh-thapliyal** [comment]
> _No description provided._

Can you share screenshot of changes made, it will be helpfull

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
can you share the snapshot of changes made, it will be helpful.

**Comment by OmDharme** [comment]
s1
s2
s3

**Review by Nitesh-thapliyal — APPROVED** [review]

**Comment by Nitesh-thapliyal** [comment]
Great work @OmDharme 🎉

**Review by adityamangal1 — APPROVED** [review]

**Pull request merged**
