### PR TITLE
Added highscore functionality and reset highscore feature

### PR DESCRIPTION
**Pull request by TDP17**
Please review this for issue #2.  
image
image

Thanks in advance 👍

### CODE REVIEW

**Review by Nitesh-thapliyal — COMMENTED** [review]
can you resolve merge conflict

**Comment by TDP17** [comment]
> can you resolve merge conflict

Resolved (I hope). 
Another unrelated issue though, game seems unplayable on desktop screens (board is too large). Should I open an issue to fix styling or will that be dealt with later? 
Thanks 👍

**Comment by kamleshjoshi8102** [comment]
> > can you resolve merge conflict
> 
> Resolved (I hope). Another unrelated issue though, game seems unplayable on desktop screens (board is too large). Should I open an issue to fix styling or will that be dealt with later? Thanks 👍

Yeah sure go ahead : ) 


And Can you host in your Github pages and share us link of that page too : )

**Review by kevalvavaliya — CHANGES_REQUESTED** [review]
@TDP17  please resolve the conflict so that we can merge your PR.
Feel free to reach us in case of any queries
Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Comment by adityamangal1** [comment]
@all-contributors please add @TDP17  for code

**Pull request merged**
