### PR TITLE
feat(start game): Added button to start game

### PR DESCRIPTION
**Pull request by aanchal-fatwani**
## Description
The requirement was to provide a feature to start the game.

A button has been added with a provision to users to start the game, instead of page load, as defined previously.

### Fixes
[Feature] Add Button to start the game #1

### CODE REVIEW

**Comment by aanchal-fatwani** [comment]
@Nitesh-thapliyal 
Kindly review the request or align the same, so as to move forward with the changes.
Thank you

**Review by kamleshjoshi8102 — CHANGES_REQUESTED** [review]
Can you share a Snapshot of your changes : )

**Review by kevalvavaliya — CHANGES_REQUESTED** [review]
please share the snapshot so that we can approve your PR 

Feel free to reach us in case of any queries
Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Comment by aanchal-fatwani** [comment]
@kamleshjoshi8102 @kevalvavaliya 
I've resolved the conflicts. 
Kindly review so as to move forward with the changes.

Here is the snapshot with updated changes:
SnakeStartButton

**Comment by adityamangal1** [comment]
@all-contributors please add @aanchal-fatwani  for code contribution

**Pull request merged**
