### PR TITLE
Align canvas to fit into full view and remove Horizontal scrolling from bottom

### PR DESCRIPTION
**Pull request by ampsteric**
This issue resolves all the bugs discussed in #4 
I have implemented all the changes as discussed and verified by @adityamangal1 and @harikanani.
Please review my PR and merge it.
@harikanani @adityamangal1 please review it and merge.
Best regards.

### CODE REVIEW

**Review by kevalvavaliya — APPROVED** [review]
LGTM

**Review by Nitesh-thapliyal — COMMENTED** [review]
can you share the snapshot of changes made, it will be helpful

**Comment by ampsteric** [comment]
sure , adding the screenshot after implementing the changes below:

**Review by kevalvavaliya — APPROVED** [review]
Great

**Comment by adityamangal1** [comment]
@all-contributors please add @ampsteric for code contribution

**Pull request merged**
